name: Building CI

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: ./api
        run: |
          mvn clean install
          mkdir ../out
          mkdir ../out/jacoco
          mkdir ../out/cucumber
          touch ../out/.nojekyll
          cp -r target/site/jacoco/* ../out/jacoco
          cp -r target/cucumber-reports/* ../out/cucumber
          cp ../reporting/index.html ../out/index.html

      - name: Set up NODE 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build with Npm
        working-directory: ./web
        run: |
          npm install
          npm run report
          mkdir ../out/angular
          cp -r coverage/url-shortener-system/* ../out/angular

      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: reporting
          folder: out
