name: Java CI

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: ./api
        run: |
          mvn clean install
          mkdir out
          mkdir out/jacoco
          mkdir out/cucumber
          touch out/.nojekyll
          cp -r target/site/jacoco/* out/jacoco
          cp -r target/cucumber-reports/* out/cucumber
          cp ../reporting/index.html out/index.html

      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: reporting
          folder: api/out
